### ISSUE TITLE
ncurses applications have some extra spacing

### ISSUE THREAD

**Issue by w8jcik** [jsmecham/atom-terminal-tab#31]
![screenshot_2017-12-17_05-58-55](https://user-images.githubusercontent.com/3964620/34076703-5e8b1d1a-e2ef-11e7-8a46-e51717126722.png)

The easiest way to reproduce this is to install midnight commander and try to run it inside Atom.

A quick fix for me was to add this to `terminal.less`:

```
terminal-view {

  .xterm {

    .xterm-rows > div {
      height: 17px;  /* needs to be font-size + 2px + padding-bottom of the span */
      font-size: 12px;
      
      & > span {
        padding-bottom: 3px;
      }
    }

  }

}
```

![screenshot_2017-12-17_16-58-06](https://user-images.githubusercontent.com/3964620/34081336-6ef69f92-e34b-11e7-8635-07184976c188.png)

But it doesn't look like a proper fix.

**Comment by HebaruSan** [comment]
I went with this in Edit &rarr; Stylesheet:

```less
terminal-view {
	// Remove padding between lines so `aptitude` looks OK
	.xterm {
		line-height: normal;
	}
}
```
