### ISSUE TITLE
themed terminal breaks stylesheets

### ISSUE THREAD

**Issue by bennypowers** [jsmecham/atom-terminal-tab#39]
Before themed terminals, this rule would style terminal as expected:

```less
terminal-view {
  .terminal {
    font-family: "Hack", monospace;
    font-size: 12px;
  }
}
```

After themed terminal was released, One must add `!important` to the rule in order for it to override the theme styles added to element.style
