### ISSUE TITLE
Change font in 0.5.0?

### ISSUE THREAD

**Issue by maxim-lian** [jsmecham/atom-terminal-tab#65]
I previously had this in my stylesheet:

```less

terminal-view {
  .xterm {
    font-family: 'M+ 1m for Powerline';
    font-size: 11pt;
  }
}
```

...with the newer canvas in 0.5.0, this doesn't seem to work. 

Is there a way of setting the font?
